version: '3'

services:

  react-web-service:
    volumes:
      - ./react-web-service:/app
      - /app/node_modules
    ports:
      - '3003:3000'
    environment:
      NODE_ENV: development

  birding-web-service:
    ports:
     - "3002:3002"
    environment:
      EXTERNAL_HOST: http://0.0.0.0:3002
      FLASK_ENV: development
