version: '3'

services:

  test-api-service:
    image: test-api-service
    container_name: test-api-service
    depends_on:
      - test-database-service
    build:
      dockerfile: testDockerfile
      context: ./api-service
    networks:
      - test
    volumes:
      - ./api-service/src/aveslog:/src/aveslog
    environment:
      EXTERNAL_HOST: myExternalHost
      DATABASE_HOST: test-database-service
      DATABASE_NAME: birding-database
      DATABASE_USER: postgres
      DATABASE_PASSWORD: docker
      FRONTEND_HOST: http://localhost:3003
    # start container with tail to keep it from stopping
    command: ["tail", "-F", "anything"]

  test-database-service:
    image: test-database-service
    container_name: test-database-service
    build:
      dockerfile: testDockerfile
      context: ./database
    networks:
      - test
    volumes:
      - ./volumes/test-database:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: birding-database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker

networks:
  test:
    driver: bridge
