version: '3'

services:

  frontend-service:
    volumes:
      - ./frontend-service/server:/app
      - ./frontend-service/client:/app/client
      # To exclude node_modules from volumes above, we make them their own
      # persistent volumes, https://stackoverflow.com/a/37898591/5638572
      - /app/node_modules
      - /app/client/node_modules
    ports:
      - '5000:3000' # dev-client
      - '3003:3003' # server
    environment:
      REACT_APP_APP_VERSION: "${FRONTEND_APP_VERSION}"
      CI: 'true' # otherwise react exits with 0 immediately
      NODE_ENV: development

  api-service:
    ports:
     - "3002:3002"
    environment:
      EXTERNAL_HOST: http://0.0.0.0:3002
      FLASK_ENV: development
      FRONTEND_HOST: http://localhost:5000
