version: '3'

services:

  frontend-service:
    container_name: frontend-service
    build:
      dockerfile: Dockerfile
      context: ./frontend-service
      args:
        appversion: "${FRONTEND_APP_VERSION}"
    image: frontend-service
    restart: always
    networks:
      - default

  api-service:
    build:
      dockerfile: Dockerfile
      context: ./api-service
    image: api-service
    container_name: api-service
    restart: always
    networks:
      - default
      - database-network
    depends_on:
      - database-service
    environment:
      DATABASE_HOST: database-service
      DATABASE_NAME: birding-database
      DATABASE_USER: postgres
      DATABASE_PASSWORD: docker
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  database-service:
    build:
      dockerfile: Dockerfile
      context: ./database
    image: database-service
    container_name: database-service
    restart: always
    networks:
      - database-network
    volumes:
      - ./volumes/database:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: birding-database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker

networks:
  database-network:
    driver: bridge
  default:
    driver: bridge
