version: '3'

services:

  frontend-service:
    volumes:
      - ./frontend-service:/app
      - /app/node_modules
    ports:
      - '3003:3000'
    environment:
      API_URL: http://127.0.0.1:3002
      NODE_ENV: development

  api-service:
    ports:
     - "3002:3002"
    environment:
      EXTERNAL_HOST: http://0.0.0.0:3002
      FLASK_ENV: development
      FRONTEND_HOST: http://localhost:3003
