version: '3'

services:

  react-web-service:
    container_name: react-web-service
    build:
      dockerfile: Dockerfile
      context: ./react-web-service
    image: react-web-service
    restart: always
    networks:
      - default

  birding-web-service:
    build:
      dockerfile: Dockerfile
      context: ./web-service
    image: birding-web-service
    volumes:
      - ./web-service/src/logs:/src/logs
    container_name: birding-web-service
    restart: always
    networks:
      - default
      - birding-database-network
    depends_on:
      - birding-database-service
    environment:
      DATABASE_HOST: birding-database-service
      DATABASE_NAME: birding-database
      DATABASE_USER: postgres
      DATABASE_PASSWORD: docker

  birding-database-service:
    build:
      dockerfile: Dockerfile
      context: ./database
    image: birding-database-service
    container_name: birding-database-service
    restart: always
    networks:
      - birding-database-network
    volumes:
      - ./volumes/database:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: birding-database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker

networks:
  birding-database-network:
    driver: bridge
  default:
    driver: bridge
