\i /schema/public/table/account.sql
\i /schema/public/table/account_registration.sql
\i /schema/public/table/bird.sql
\i /schema/public/table/bird_thumbnail.sql
\i /schema/public/table/hashed_password.sql
\i /schema/public/table/locale.sql
\i /schema/public/table/password_reset_token.sql
\i /schema/public/table/birder.sql
\i /schema/public/table/picture.sql
\i /schema/public/table/refresh_token.sql
\i /schema/public/table/sighting.sql
\i /schema/public/table/bird_name.sql

\i /schema/public/foreign-key-constraint/account.sql
\i /schema/public/foreign-key-constraint/bird_thumbnail.sql
\i /schema/public/foreign-key-constraint/hashed_password.sql
\i /schema/public/foreign-key-constraint/password_reset_token.sql
\i /schema/public/foreign-key-constraint/refresh_token.sql
\i /schema/public/foreign-key-constraint/sighting.sql
\i /schema/public/foreign-key-constraint/bird_name.sql
