\i /schema/public/table/account.sql
\i /schema/public/table/registration_request.sql
\i /schema/public/table/bird.sql
\i /schema/public/table/bird_thumbnail.sql
\i /schema/public/table/hashed_password.sql
\i /schema/public/table/locale.sql
\i /schema/public/table/password_reset_token.sql
\i /schema/public/table/birder.sql
\i /schema/public/table/picture.sql
\i /schema/public/table/refresh_token.sql
\i /schema/public/table/sighting.sql
\i /schema/public/table/bird_common_name.sql
\i /schema/public/table/position.sql
\i /schema/public/table/position_name.sql
\i /schema/public/table/role.sql
\i /schema/public/table/account_role.sql
\i /schema/public/table/resource_permission.sql
\i /schema/public/table/role_resource_permission.sql
\i /schema/public/table/birder_connection.sql

\i /schema/public/foreign-key-constraint/account.sql
\i /schema/public/foreign-key-constraint/bird_thumbnail.sql
\i /schema/public/foreign-key-constraint/hashed_password.sql
\i /schema/public/foreign-key-constraint/password_reset_token.sql
\i /schema/public/foreign-key-constraint/refresh_token.sql
\i /schema/public/foreign-key-constraint/sighting.sql
\i /schema/public/foreign-key-constraint/bird_common_name.sql
\i /schema/public/foreign-key-constraint/position_name.sql
\i /schema/public/foreign-key-constraint/account_role.sql
\i /schema/public/foreign-key-constraint/role_resource_permission.sql
\i /schema/public/foreign-key-constraint/birder_connection.sql
