FROM node:10
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY package.json /app/package.json
RUN npm install --package-lock-only
RUN npm audit fix
RUN npm install
RUN npm install react-scripts@3.0.1 -g
COPY . /app
ARG apiurl
ENV API_URL=${apiurl}
ARG appversion
ENV APP_VERSION=${appversion}
RUN ./env.sh
RUN npm run build
CMD ["npm", "run", "start"]
