FROM node:10

# install server and client dependencies
WORKDIR /app
COPY server/package*.json ./
RUN npm install
WORKDIR /client
COPY client/package*.json ./
RUN npm install

# copy server and client src
COPY server /app/
COPY client /client/

# build client
ARG appversion
ENV REACT_APP_APP_VERSION=${appversion}
RUN npm run build

# move client build into app
RUN mv build /app/client/build

WORKDIR /app

CMD ["npm", "run", "server"]
